name: Deploy Application
on: push
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$BALKAN_PRIV" > ../private.key
          sudo chmod 600 ../private.key
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BALKAN_PRIV }}
          SSH_KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          USER_AT_HOST: ${{ secrets.USER_AT_HOST }}
      - name: Create test file on server
        run: |
          ssh -i "$SSH_KEY_PATH" "$USER_AT_HOST"
          touch testing.txt
